# Generated by Django 3.2.5 on 2021-07-10 20:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('账户名称', models.CharField(max_length=100)),
                ('余额', models.DecimalField(decimal_places=2, max_digits=8)),
                ('图标', models.CharField(max_length=100, null=True)),
                ('创建时间', models.DateTimeField(auto_now_add=True)),
                ('修改时间', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '账户',
                'verbose_name_plural': '账户',
                'ordering': ['创建时间'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('分类名', models.CharField(max_length=100)),
                ('收支类型', models.CharField(choices=[('expense', '支出'), ('income', '收入')], default='expense', max_length=100)),
            ],
            options={
                'verbose_name': '分类',
                'verbose_name_plural': '分类',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TransferRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('转移时间', models.DateTimeField(default=django.utils.timezone.now)),
                ('转移金额', models.DecimalField(decimal_places=2, max_digits=8)),
                ('备注', models.CharField(blank=True, max_length=500, null=True)),
                ('从哪个账户转移', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_account', to='billing.account')),
                ('转移到哪个账户', models.ForeignKey(default=2, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='to_account', to='billing.account')),
            ],
            options={
                'ordering': ['-转移时间'],
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('分类名', models.CharField(max_length=100)),
                ('父级分类', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.category')),
            ],
            options={
                'verbose_name': '子分类',
                'verbose_name_plural': '子分类',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='HistoryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('记录时间', models.DateTimeField(default=django.utils.timezone.now)),
                ('金额', models.DecimalField(decimal_places=2, max_digits=8)),
                ('备注', models.CharField(blank=True, max_length=500, null=True)),
                ('创建时间', models.DateTimeField(auto_now_add=True)),
                ('修改时间', models.DateTimeField(auto_now=True)),
                ('子级分类', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.subcategory')),
                ('父级分类', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.category')),
                ('账户', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.account')),
            ],
            options={
                'verbose_name': '账单记录',
                'verbose_name_plural': '账单记录',
                'ordering': ['-记录时间'],
            },
        ),
    ]
